# Generated by Django 3.2.14 on 2022-07-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_budgets', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('TRANSPORTATION', 'Transportation'), ('FOOD', 'Food'), ('MEDICAL_AND_HEALTHCARE', 'Medical & Healthcare'), ('UTILITIES', 'Utilities'), ('SAVING_AND_DEBT_PAYMENTS', 'Saving & Debt Payments'), ('INSURANCE', 'Insurance'), ('WORK', 'Work'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='family_budget.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('TRANSPORTATION', 'Transportation'), ('FOOD', 'Food'), ('MEDICAL_AND_HEALTHCARE', 'Medical & Healthcare'), ('UTILITIES', 'Utilities'), ('SAVING_AND_DEBT_PAYMENTS', 'Saving & Debt Payments'), ('INSURANCE', 'Insurance'), ('WORK', 'Work'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='family_budget.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
